//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBot.MonitorServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthereumStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GpuTemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DcrInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RunningTime {
            get {
                return this.RunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningTimeField, value) != true)) {
                    this.RunningTimeField = value;
                    this.RaisePropertyChanged("RunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EthereumStats {
            get {
                return this.EthereumStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.EthereumStatsField, value) != true)) {
                    this.EthereumStatsField = value;
                    this.RaisePropertyChanged("EthereumStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GpuTemperature {
            get {
                return this.GpuTemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.GpuTemperatureField, value) != true)) {
                    this.GpuTemperatureField = value;
                    this.RaisePropertyChanged("GpuTemperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Pool {
            get {
                return this.PoolField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolField, value) != true)) {
                    this.PoolField = value;
                    this.RaisePropertyChanged("Pool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DcrInfo {
            get {
                return this.DcrInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DcrInfoField, value) != true)) {
                    this.DcrInfoField = value;
                    this.RaisePropertyChanged("DcrInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorServices.MonitorServicesSoap")]
    public interface MonitorServicesSoap {
        
        // CODEGEN: Generating message contract since element name minerInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        VBot.MonitorServices.InsertMinerResponse InsertMiner(VBot.MonitorServices.InsertMinerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        System.Threading.Tasks.Task<VBot.MonitorServices.InsertMinerResponse> InsertMinerAsync(VBot.MonitorServices.InsertMinerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMinerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMiner", Namespace="http://tempuri.org/", Order=0)]
        public VBot.MonitorServices.InsertMinerRequestBody Body;
        
        public InsertMinerRequest() {
        }
        
        public InsertMinerRequest(VBot.MonitorServices.InsertMinerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMinerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VBot.MonitorServices.MinerInfo minerInfo;
        
        public InsertMinerRequestBody() {
        }
        
        public InsertMinerRequestBody(VBot.MonitorServices.MinerInfo minerInfo) {
            this.minerInfo = minerInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMinerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMinerResponse", Namespace="http://tempuri.org/", Order=0)]
        public VBot.MonitorServices.InsertMinerResponseBody Body;
        
        public InsertMinerResponse() {
        }
        
        public InsertMinerResponse(VBot.MonitorServices.InsertMinerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMinerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertMinerResult;
        
        public InsertMinerResponseBody() {
        }
        
        public InsertMinerResponseBody(string InsertMinerResult) {
            this.InsertMinerResult = InsertMinerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorServicesSoapChannel : VBot.MonitorServices.MonitorServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorServicesSoapClient : System.ServiceModel.ClientBase<VBot.MonitorServices.MonitorServicesSoap>, VBot.MonitorServices.MonitorServicesSoap {
        
        public MonitorServicesSoapClient() {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VBot.MonitorServices.InsertMinerResponse VBot.MonitorServices.MonitorServicesSoap.InsertMiner(VBot.MonitorServices.InsertMinerRequest request) {
            return base.Channel.InsertMiner(request);
        }
        
        public string InsertMiner(VBot.MonitorServices.MinerInfo minerInfo) {
            VBot.MonitorServices.InsertMinerRequest inValue = new VBot.MonitorServices.InsertMinerRequest();
            inValue.Body = new VBot.MonitorServices.InsertMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            VBot.MonitorServices.InsertMinerResponse retVal = ((VBot.MonitorServices.MonitorServicesSoap)(this)).InsertMiner(inValue);
            return retVal.Body.InsertMinerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VBot.MonitorServices.InsertMinerResponse> VBot.MonitorServices.MonitorServicesSoap.InsertMinerAsync(VBot.MonitorServices.InsertMinerRequest request) {
            return base.Channel.InsertMinerAsync(request);
        }
        
        public System.Threading.Tasks.Task<VBot.MonitorServices.InsertMinerResponse> InsertMinerAsync(VBot.MonitorServices.MinerInfo minerInfo) {
            VBot.MonitorServices.InsertMinerRequest inValue = new VBot.MonitorServices.InsertMinerRequest();
            inValue.Body = new VBot.MonitorServices.InsertMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            return ((VBot.MonitorServices.MonitorServicesSoap)(this)).InsertMinerAsync(inValue);
        }
    }
}
