//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthMonitorApp.MonitorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.Worker[] WorkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerStatistics StatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerHistory[] HistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerPayouts[] PayoutsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerRounds[] RoundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerSettings SettingsField;
        
        private System.DateTime CreatedDateField;
        
        private System.DateTime StatisticsDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Wallet {
            get {
                return this.WalletField;
            }
            set {
                if ((object.ReferenceEquals(this.WalletField, value) != true)) {
                    this.WalletField = value;
                    this.RaisePropertyChanged("Wallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EthMonitorApp.MonitorService.Worker[] Workers {
            get {
                return this.WorkersField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkersField, value) != true)) {
                    this.WorkersField = value;
                    this.RaisePropertyChanged("Workers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EthMonitorApp.MonitorService.MinerStatistics Stats {
            get {
                return this.StatsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatsField, value) != true)) {
                    this.StatsField = value;
                    this.RaisePropertyChanged("Stats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public EthMonitorApp.MonitorService.MinerHistory[] History {
            get {
                return this.HistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoryField, value) != true)) {
                    this.HistoryField = value;
                    this.RaisePropertyChanged("History");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EthMonitorApp.MonitorService.MinerPayouts[] Payouts {
            get {
                return this.PayoutsField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutsField, value) != true)) {
                    this.PayoutsField = value;
                    this.RaisePropertyChanged("Payouts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public EthMonitorApp.MonitorService.MinerRounds[] Rounds {
            get {
                return this.RoundsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundsField, value) != true)) {
                    this.RoundsField = value;
                    this.RaisePropertyChanged("Rounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public EthMonitorApp.MonitorService.MinerSettings Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime StatisticsDate {
            get {
                return this.StatisticsDateField;
            }
            set {
                if ((this.StatisticsDateField.Equals(value) != true)) {
                    this.StatisticsDateField = value;
                    this.RaisePropertyChanged("StatisticsDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerStatistics", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerSettings))]
    public partial class MinerStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int timeField;
        
        private int lastSeenField;
        
        private int reportedHashrateField;
        
        private double currentHashrateField;
        
        private int validSharesField;
        
        private int invalidSharesField;
        
        private int staleSharesField;
        
        private double averageHashrateField;
        
        private int activeWorkersField;
        
        private long unpaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object unconfirmedField;
        
        private double coinsPerMinField;
        
        private double usdPerMinField;
        
        private double btcPerMinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int lastSeen {
            get {
                return this.lastSeenField;
            }
            set {
                if ((this.lastSeenField.Equals(value) != true)) {
                    this.lastSeenField = value;
                    this.RaisePropertyChanged("lastSeen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int reportedHashrate {
            get {
                return this.reportedHashrateField;
            }
            set {
                if ((this.reportedHashrateField.Equals(value) != true)) {
                    this.reportedHashrateField = value;
                    this.RaisePropertyChanged("reportedHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double currentHashrate {
            get {
                return this.currentHashrateField;
            }
            set {
                if ((this.currentHashrateField.Equals(value) != true)) {
                    this.currentHashrateField = value;
                    this.RaisePropertyChanged("currentHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int validShares {
            get {
                return this.validSharesField;
            }
            set {
                if ((this.validSharesField.Equals(value) != true)) {
                    this.validSharesField = value;
                    this.RaisePropertyChanged("validShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int invalidShares {
            get {
                return this.invalidSharesField;
            }
            set {
                if ((this.invalidSharesField.Equals(value) != true)) {
                    this.invalidSharesField = value;
                    this.RaisePropertyChanged("invalidShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int staleShares {
            get {
                return this.staleSharesField;
            }
            set {
                if ((this.staleSharesField.Equals(value) != true)) {
                    this.staleSharesField = value;
                    this.RaisePropertyChanged("staleShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double averageHashrate {
            get {
                return this.averageHashrateField;
            }
            set {
                if ((this.averageHashrateField.Equals(value) != true)) {
                    this.averageHashrateField = value;
                    this.RaisePropertyChanged("averageHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int activeWorkers {
            get {
                return this.activeWorkersField;
            }
            set {
                if ((this.activeWorkersField.Equals(value) != true)) {
                    this.activeWorkersField = value;
                    this.RaisePropertyChanged("activeWorkers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long unpaid {
            get {
                return this.unpaidField;
            }
            set {
                if ((this.unpaidField.Equals(value) != true)) {
                    this.unpaidField = value;
                    this.RaisePropertyChanged("unpaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public object unconfirmed {
            get {
                return this.unconfirmedField;
            }
            set {
                if ((object.ReferenceEquals(this.unconfirmedField, value) != true)) {
                    this.unconfirmedField = value;
                    this.RaisePropertyChanged("unconfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double coinsPerMin {
            get {
                return this.coinsPerMinField;
            }
            set {
                if ((this.coinsPerMinField.Equals(value) != true)) {
                    this.coinsPerMinField = value;
                    this.RaisePropertyChanged("coinsPerMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double usdPerMin {
            get {
                return this.usdPerMinField;
            }
            set {
                if ((this.usdPerMinField.Equals(value) != true)) {
                    this.usdPerMinField = value;
                    this.RaisePropertyChanged("usdPerMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double btcPerMin {
            get {
                return this.btcPerMinField;
            }
            set {
                if ((this.btcPerMinField.Equals(value) != true)) {
                    this.btcPerMinField = value;
                    this.RaisePropertyChanged("btcPerMin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerSettings", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private int monitorField;
        
        private long minPayoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int monitor {
            get {
                return this.monitorField;
            }
            set {
                if ((this.monitorField.Equals(value) != true)) {
                    this.monitorField = value;
                    this.RaisePropertyChanged("monitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long minPayout {
            get {
                return this.minPayoutField;
            }
            set {
                if ((this.minPayoutField.Equals(value) != true)) {
                    this.minPayoutField = value;
                    this.RaisePropertyChanged("minPayout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthereumStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GpuTemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DcrInfoField;
        
        private System.DateTime CreatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RunningTime {
            get {
                return this.RunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningTimeField, value) != true)) {
                    this.RunningTimeField = value;
                    this.RaisePropertyChanged("RunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EthereumStats {
            get {
                return this.EthereumStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.EthereumStatsField, value) != true)) {
                    this.EthereumStatsField = value;
                    this.RaisePropertyChanged("EthereumStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GpuTemperature {
            get {
                return this.GpuTemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.GpuTemperatureField, value) != true)) {
                    this.GpuTemperatureField = value;
                    this.RaisePropertyChanged("GpuTemperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Pool {
            get {
                return this.PoolField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolField, value) != true)) {
                    this.PoolField = value;
                    this.RaisePropertyChanged("Pool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DcrInfo {
            get {
                return this.DcrInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DcrInfoField, value) != true)) {
                    this.DcrInfoField = value;
                    this.RaisePropertyChanged("DcrInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerHistory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int timeField;
        
        private int reportedHashrateField;
        
        private double currentHashrateField;
        
        private int validSharesField;
        
        private int invalidSharesField;
        
        private int staleSharesField;
        
        private double averageHashrateField;
        
        private int activeWorkersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int reportedHashrate {
            get {
                return this.reportedHashrateField;
            }
            set {
                if ((this.reportedHashrateField.Equals(value) != true)) {
                    this.reportedHashrateField = value;
                    this.RaisePropertyChanged("reportedHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double currentHashrate {
            get {
                return this.currentHashrateField;
            }
            set {
                if ((this.currentHashrateField.Equals(value) != true)) {
                    this.currentHashrateField = value;
                    this.RaisePropertyChanged("currentHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int validShares {
            get {
                return this.validSharesField;
            }
            set {
                if ((this.validSharesField.Equals(value) != true)) {
                    this.validSharesField = value;
                    this.RaisePropertyChanged("validShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int invalidShares {
            get {
                return this.invalidSharesField;
            }
            set {
                if ((this.invalidSharesField.Equals(value) != true)) {
                    this.invalidSharesField = value;
                    this.RaisePropertyChanged("invalidShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int staleShares {
            get {
                return this.staleSharesField;
            }
            set {
                if ((this.staleSharesField.Equals(value) != true)) {
                    this.staleSharesField = value;
                    this.RaisePropertyChanged("staleShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double averageHashrate {
            get {
                return this.averageHashrateField;
            }
            set {
                if ((this.averageHashrateField.Equals(value) != true)) {
                    this.averageHashrateField = value;
                    this.RaisePropertyChanged("averageHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int activeWorkers {
            get {
                return this.activeWorkersField;
            }
            set {
                if ((this.activeWorkersField.Equals(value) != true)) {
                    this.activeWorkersField = value;
                    this.RaisePropertyChanged("activeWorkers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerPayouts", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerStatistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerSettings))]
    public partial class MinerPayouts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int startField;
        
        private int endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txHashField;
        
        private int paidOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int end {
            get {
                return this.endField;
            }
            set {
                if ((this.endField.Equals(value) != true)) {
                    this.endField = value;
                    this.RaisePropertyChanged("end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txHash {
            get {
                return this.txHashField;
            }
            set {
                if ((object.ReferenceEquals(this.txHashField, value) != true)) {
                    this.txHashField = value;
                    this.RaisePropertyChanged("txHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int paidOn {
            get {
                return this.paidOnField;
            }
            set {
                if ((this.paidOnField.Equals(value) != true)) {
                    this.paidOnField = value;
                    this.RaisePropertyChanged("paidOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerRounds", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerStatistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerSettings))]
    public partial class MinerRounds : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int blockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object amountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int block {
            get {
                return this.blockField;
            }
            set {
                if ((this.blockField.Equals(value) != true)) {
                    this.blockField = value;
                    this.RaisePropertyChanged("block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorService.MonitorServicesSoap")]
    public interface MonitorServicesSoap {
        
        // CODEGEN: Generating message contract since element name CheckVerionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVerion", ReplyAction="*")]
        EthMonitorApp.MonitorService.CheckVerionResponse CheckVerion(EthMonitorApp.MonitorService.CheckVerionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVerion", ReplyAction="*")]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckVerionResponse> CheckVerionAsync(EthMonitorApp.MonitorService.CheckVerionRequest request);
        
        // CODEGEN: Generating message contract since element name minerInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendtMiner", ReplyAction="*")]
        EthMonitorApp.MonitorService.SendtMinerResponse SendtMiner(EthMonitorApp.MonitorService.SendtMinerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendtMiner", ReplyAction="*")]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.SendtMinerResponse> SendtMinerAsync(EthMonitorApp.MonitorService.SendtMinerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVerionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVerion", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.CheckVerionRequestBody Body;
        
        public CheckVerionRequest() {
        }
        
        public CheckVerionRequest(EthMonitorApp.MonitorService.CheckVerionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckVerionRequestBody {
        
        public CheckVerionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVerionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVerionResponse", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.CheckVerionResponseBody Body;
        
        public CheckVerionResponse() {
        }
        
        public CheckVerionResponse(EthMonitorApp.MonitorService.CheckVerionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckVerionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckVerionResult;
        
        public CheckVerionResponseBody() {
        }
        
        public CheckVerionResponseBody(string CheckVerionResult) {
            this.CheckVerionResult = CheckVerionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendtMinerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendtMiner", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.SendtMinerRequestBody Body;
        
        public SendtMinerRequest() {
        }
        
        public SendtMinerRequest(EthMonitorApp.MonitorService.SendtMinerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendtMinerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EthMonitorApp.MonitorService.MinerInfo minerInfo;
        
        public SendtMinerRequestBody() {
        }
        
        public SendtMinerRequestBody(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            this.minerInfo = minerInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendtMinerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendtMinerResponse", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.SendtMinerResponseBody Body;
        
        public SendtMinerResponse() {
        }
        
        public SendtMinerResponse(EthMonitorApp.MonitorService.SendtMinerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendtMinerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendtMinerResult;
        
        public SendtMinerResponseBody() {
        }
        
        public SendtMinerResponseBody(string SendtMinerResult) {
            this.SendtMinerResult = SendtMinerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorServicesSoapChannel : EthMonitorApp.MonitorService.MonitorServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorServicesSoapClient : System.ServiceModel.ClientBase<EthMonitorApp.MonitorService.MonitorServicesSoap>, EthMonitorApp.MonitorService.MonitorServicesSoap {
        
        public MonitorServicesSoapClient() {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EthMonitorApp.MonitorService.CheckVerionResponse EthMonitorApp.MonitorService.MonitorServicesSoap.CheckVerion(EthMonitorApp.MonitorService.CheckVerionRequest request) {
            return base.Channel.CheckVerion(request);
        }
        
        public string CheckVerion() {
            EthMonitorApp.MonitorService.CheckVerionRequest inValue = new EthMonitorApp.MonitorService.CheckVerionRequest();
            inValue.Body = new EthMonitorApp.MonitorService.CheckVerionRequestBody();
            EthMonitorApp.MonitorService.CheckVerionResponse retVal = ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).CheckVerion(inValue);
            return retVal.Body.CheckVerionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckVerionResponse> EthMonitorApp.MonitorService.MonitorServicesSoap.CheckVerionAsync(EthMonitorApp.MonitorService.CheckVerionRequest request) {
            return base.Channel.CheckVerionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckVerionResponse> CheckVerionAsync() {
            EthMonitorApp.MonitorService.CheckVerionRequest inValue = new EthMonitorApp.MonitorService.CheckVerionRequest();
            inValue.Body = new EthMonitorApp.MonitorService.CheckVerionRequestBody();
            return ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).CheckVerionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EthMonitorApp.MonitorService.SendtMinerResponse EthMonitorApp.MonitorService.MonitorServicesSoap.SendtMiner(EthMonitorApp.MonitorService.SendtMinerRequest request) {
            return base.Channel.SendtMiner(request);
        }
        
        public string SendtMiner(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            EthMonitorApp.MonitorService.SendtMinerRequest inValue = new EthMonitorApp.MonitorService.SendtMinerRequest();
            inValue.Body = new EthMonitorApp.MonitorService.SendtMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            EthMonitorApp.MonitorService.SendtMinerResponse retVal = ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).SendtMiner(inValue);
            return retVal.Body.SendtMinerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.SendtMinerResponse> EthMonitorApp.MonitorService.MonitorServicesSoap.SendtMinerAsync(EthMonitorApp.MonitorService.SendtMinerRequest request) {
            return base.Channel.SendtMinerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EthMonitorApp.MonitorService.SendtMinerResponse> SendtMinerAsync(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            EthMonitorApp.MonitorService.SendtMinerRequest inValue = new EthMonitorApp.MonitorService.SendtMinerRequest();
            inValue.Body = new EthMonitorApp.MonitorService.SendtMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            return ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).SendtMinerAsync(inValue);
        }
    }
}
