//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthMonitorApp.MonitorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.Worker[] WorkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerStatistics MinerStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerHistory[] MinerHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerPayouts[] MinerPayoutsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EthMonitorApp.MonitorService.MinerRounds[] MinerRoundsField;
        
        private System.DateTime CreatedDateField;
        
        private System.DateTime StatisticsDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Wallet {
            get {
                return this.WalletField;
            }
            set {
                if ((object.ReferenceEquals(this.WalletField, value) != true)) {
                    this.WalletField = value;
                    this.RaisePropertyChanged("Wallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EthMonitorApp.MonitorService.Worker[] Workers {
            get {
                return this.WorkersField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkersField, value) != true)) {
                    this.WorkersField = value;
                    this.RaisePropertyChanged("Workers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EthMonitorApp.MonitorService.MinerStatistics MinerStats {
            get {
                return this.MinerStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.MinerStatsField, value) != true)) {
                    this.MinerStatsField = value;
                    this.RaisePropertyChanged("MinerStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public EthMonitorApp.MonitorService.MinerHistory[] MinerHistory {
            get {
                return this.MinerHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.MinerHistoryField, value) != true)) {
                    this.MinerHistoryField = value;
                    this.RaisePropertyChanged("MinerHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EthMonitorApp.MonitorService.MinerPayouts[] MinerPayouts {
            get {
                return this.MinerPayoutsField;
            }
            set {
                if ((object.ReferenceEquals(this.MinerPayoutsField, value) != true)) {
                    this.MinerPayoutsField = value;
                    this.RaisePropertyChanged("MinerPayouts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public EthMonitorApp.MonitorService.MinerRounds[] MinerRounds {
            get {
                return this.MinerRoundsField;
            }
            set {
                if ((object.ReferenceEquals(this.MinerRoundsField, value) != true)) {
                    this.MinerRoundsField = value;
                    this.RaisePropertyChanged("MinerRounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime StatisticsDate {
            get {
                return this.StatisticsDateField;
            }
            set {
                if ((this.StatisticsDateField.Equals(value) != true)) {
                    this.StatisticsDateField = value;
                    this.RaisePropertyChanged("StatisticsDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerStatistics", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds))]
    public partial class MinerStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int timeField;
        
        private int lastSeenField;
        
        private int reportedHashrateField;
        
        private double currentHashrateField;
        
        private int validSharesField;
        
        private int invalidSharesField;
        
        private int staleSharesField;
        
        private double averageHashrateField;
        
        private int activeWorkersField;
        
        private long unpaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object unconfirmedField;
        
        private double coinsPerMinField;
        
        private double usdPerMinField;
        
        private double btcPerMinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int lastSeen {
            get {
                return this.lastSeenField;
            }
            set {
                if ((this.lastSeenField.Equals(value) != true)) {
                    this.lastSeenField = value;
                    this.RaisePropertyChanged("lastSeen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int reportedHashrate {
            get {
                return this.reportedHashrateField;
            }
            set {
                if ((this.reportedHashrateField.Equals(value) != true)) {
                    this.reportedHashrateField = value;
                    this.RaisePropertyChanged("reportedHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double currentHashrate {
            get {
                return this.currentHashrateField;
            }
            set {
                if ((this.currentHashrateField.Equals(value) != true)) {
                    this.currentHashrateField = value;
                    this.RaisePropertyChanged("currentHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int validShares {
            get {
                return this.validSharesField;
            }
            set {
                if ((this.validSharesField.Equals(value) != true)) {
                    this.validSharesField = value;
                    this.RaisePropertyChanged("validShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int invalidShares {
            get {
                return this.invalidSharesField;
            }
            set {
                if ((this.invalidSharesField.Equals(value) != true)) {
                    this.invalidSharesField = value;
                    this.RaisePropertyChanged("invalidShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int staleShares {
            get {
                return this.staleSharesField;
            }
            set {
                if ((this.staleSharesField.Equals(value) != true)) {
                    this.staleSharesField = value;
                    this.RaisePropertyChanged("staleShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double averageHashrate {
            get {
                return this.averageHashrateField;
            }
            set {
                if ((this.averageHashrateField.Equals(value) != true)) {
                    this.averageHashrateField = value;
                    this.RaisePropertyChanged("averageHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int activeWorkers {
            get {
                return this.activeWorkersField;
            }
            set {
                if ((this.activeWorkersField.Equals(value) != true)) {
                    this.activeWorkersField = value;
                    this.RaisePropertyChanged("activeWorkers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long unpaid {
            get {
                return this.unpaidField;
            }
            set {
                if ((this.unpaidField.Equals(value) != true)) {
                    this.unpaidField = value;
                    this.RaisePropertyChanged("unpaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public object unconfirmed {
            get {
                return this.unconfirmedField;
            }
            set {
                if ((object.ReferenceEquals(this.unconfirmedField, value) != true)) {
                    this.unconfirmedField = value;
                    this.RaisePropertyChanged("unconfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double coinsPerMin {
            get {
                return this.coinsPerMinField;
            }
            set {
                if ((this.coinsPerMinField.Equals(value) != true)) {
                    this.coinsPerMinField = value;
                    this.RaisePropertyChanged("coinsPerMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double usdPerMin {
            get {
                return this.usdPerMinField;
            }
            set {
                if ((this.usdPerMinField.Equals(value) != true)) {
                    this.usdPerMinField = value;
                    this.RaisePropertyChanged("usdPerMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double btcPerMin {
            get {
                return this.btcPerMinField;
            }
            set {
                if ((this.btcPerMinField.Equals(value) != true)) {
                    this.btcPerMinField = value;
                    this.RaisePropertyChanged("btcPerMin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthereumStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GpuTemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DcrInfoField;
        
        private System.DateTime CreatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RunningTime {
            get {
                return this.RunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningTimeField, value) != true)) {
                    this.RunningTimeField = value;
                    this.RaisePropertyChanged("RunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EthereumStats {
            get {
                return this.EthereumStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.EthereumStatsField, value) != true)) {
                    this.EthereumStatsField = value;
                    this.RaisePropertyChanged("EthereumStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GpuTemperature {
            get {
                return this.GpuTemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.GpuTemperatureField, value) != true)) {
                    this.GpuTemperatureField = value;
                    this.RaisePropertyChanged("GpuTemperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Pool {
            get {
                return this.PoolField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolField, value) != true)) {
                    this.PoolField = value;
                    this.RaisePropertyChanged("Pool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DcrInfo {
            get {
                return this.DcrInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DcrInfoField, value) != true)) {
                    this.DcrInfoField = value;
                    this.RaisePropertyChanged("DcrInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerHistory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MinerHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int timeField;
        
        private int reportedHashrateField;
        
        private double currentHashrateField;
        
        private int validSharesField;
        
        private int invalidSharesField;
        
        private int staleSharesField;
        
        private double averageHashrateField;
        
        private int activeWorkersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int reportedHashrate {
            get {
                return this.reportedHashrateField;
            }
            set {
                if ((this.reportedHashrateField.Equals(value) != true)) {
                    this.reportedHashrateField = value;
                    this.RaisePropertyChanged("reportedHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double currentHashrate {
            get {
                return this.currentHashrateField;
            }
            set {
                if ((this.currentHashrateField.Equals(value) != true)) {
                    this.currentHashrateField = value;
                    this.RaisePropertyChanged("currentHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int validShares {
            get {
                return this.validSharesField;
            }
            set {
                if ((this.validSharesField.Equals(value) != true)) {
                    this.validSharesField = value;
                    this.RaisePropertyChanged("validShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int invalidShares {
            get {
                return this.invalidSharesField;
            }
            set {
                if ((this.invalidSharesField.Equals(value) != true)) {
                    this.invalidSharesField = value;
                    this.RaisePropertyChanged("invalidShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int staleShares {
            get {
                return this.staleSharesField;
            }
            set {
                if ((this.staleSharesField.Equals(value) != true)) {
                    this.staleSharesField = value;
                    this.RaisePropertyChanged("staleShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double averageHashrate {
            get {
                return this.averageHashrateField;
            }
            set {
                if ((this.averageHashrateField.Equals(value) != true)) {
                    this.averageHashrateField = value;
                    this.RaisePropertyChanged("averageHashrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int activeWorkers {
            get {
                return this.activeWorkersField;
            }
            set {
                if ((this.activeWorkersField.Equals(value) != true)) {
                    this.activeWorkersField = value;
                    this.RaisePropertyChanged("activeWorkers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerPayouts", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerStatistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds))]
    public partial class MinerPayouts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int startField;
        
        private int endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txHashField;
        
        private int paidOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int end {
            get {
                return this.endField;
            }
            set {
                if ((this.endField.Equals(value) != true)) {
                    this.endField = value;
                    this.RaisePropertyChanged("end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txHash {
            get {
                return this.txHashField;
            }
            set {
                if ((object.ReferenceEquals(this.txHashField, value) != true)) {
                    this.txHashField = value;
                    this.RaisePropertyChanged("txHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int paidOn {
            get {
                return this.paidOnField;
            }
            set {
                if ((this.paidOnField.Equals(value) != true)) {
                    this.paidOnField = value;
                    this.RaisePropertyChanged("paidOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinerRounds", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerStatistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerPayouts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EthMonitorApp.MonitorService.MinerRounds[]))]
    public partial class MinerRounds : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int blockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object amountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int block {
            get {
                return this.blockField;
            }
            set {
                if ((this.blockField.Equals(value) != true)) {
                    this.blockField = value;
                    this.RaisePropertyChanged("block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorService.MonitorServicesSoap")]
    public interface MonitorServicesSoap {
        
        // CODEGEN: Generating message contract since element name minerInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        EthMonitorApp.MonitorService.InsertMinerResponse InsertMiner(EthMonitorApp.MonitorService.InsertMinerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.InsertMinerResponse> InsertMinerAsync(EthMonitorApp.MonitorService.InsertMinerRequest request);
        
        // CODEGEN: Generating message contract since element name uniqueName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMinerName", ReplyAction="*")]
        EthMonitorApp.MonitorService.CheckMinerNameResponse CheckMinerName(EthMonitorApp.MonitorService.CheckMinerNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMinerName", ReplyAction="*")]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckMinerNameResponse> CheckMinerNameAsync(EthMonitorApp.MonitorService.CheckMinerNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMinerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMiner", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.InsertMinerRequestBody Body;
        
        public InsertMinerRequest() {
        }
        
        public InsertMinerRequest(EthMonitorApp.MonitorService.InsertMinerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMinerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EthMonitorApp.MonitorService.MinerInfo minerInfo;
        
        public InsertMinerRequestBody() {
        }
        
        public InsertMinerRequestBody(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            this.minerInfo = minerInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMinerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMinerResponse", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.InsertMinerResponseBody Body;
        
        public InsertMinerResponse() {
        }
        
        public InsertMinerResponse(EthMonitorApp.MonitorService.InsertMinerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMinerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertMinerResult;
        
        public InsertMinerResponseBody() {
        }
        
        public InsertMinerResponseBody(string InsertMinerResult) {
            this.InsertMinerResult = InsertMinerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMinerNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMinerName", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.CheckMinerNameRequestBody Body;
        
        public CheckMinerNameRequest() {
        }
        
        public CheckMinerNameRequest(EthMonitorApp.MonitorService.CheckMinerNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMinerNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uniqueName;
        
        public CheckMinerNameRequestBody() {
        }
        
        public CheckMinerNameRequestBody(string uniqueName) {
            this.uniqueName = uniqueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMinerNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMinerNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public EthMonitorApp.MonitorService.CheckMinerNameResponseBody Body;
        
        public CheckMinerNameResponse() {
        }
        
        public CheckMinerNameResponse(EthMonitorApp.MonitorService.CheckMinerNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMinerNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckMinerNameResult;
        
        public CheckMinerNameResponseBody() {
        }
        
        public CheckMinerNameResponseBody(bool CheckMinerNameResult) {
            this.CheckMinerNameResult = CheckMinerNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorServicesSoapChannel : EthMonitorApp.MonitorService.MonitorServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorServicesSoapClient : System.ServiceModel.ClientBase<EthMonitorApp.MonitorService.MonitorServicesSoap>, EthMonitorApp.MonitorService.MonitorServicesSoap {
        
        public MonitorServicesSoapClient() {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EthMonitorApp.MonitorService.InsertMinerResponse EthMonitorApp.MonitorService.MonitorServicesSoap.InsertMiner(EthMonitorApp.MonitorService.InsertMinerRequest request) {
            return base.Channel.InsertMiner(request);
        }
        
        public string InsertMiner(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            EthMonitorApp.MonitorService.InsertMinerRequest inValue = new EthMonitorApp.MonitorService.InsertMinerRequest();
            inValue.Body = new EthMonitorApp.MonitorService.InsertMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            EthMonitorApp.MonitorService.InsertMinerResponse retVal = ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).InsertMiner(inValue);
            return retVal.Body.InsertMinerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.InsertMinerResponse> EthMonitorApp.MonitorService.MonitorServicesSoap.InsertMinerAsync(EthMonitorApp.MonitorService.InsertMinerRequest request) {
            return base.Channel.InsertMinerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EthMonitorApp.MonitorService.InsertMinerResponse> InsertMinerAsync(EthMonitorApp.MonitorService.MinerInfo minerInfo) {
            EthMonitorApp.MonitorService.InsertMinerRequest inValue = new EthMonitorApp.MonitorService.InsertMinerRequest();
            inValue.Body = new EthMonitorApp.MonitorService.InsertMinerRequestBody();
            inValue.Body.minerInfo = minerInfo;
            return ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).InsertMinerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EthMonitorApp.MonitorService.CheckMinerNameResponse EthMonitorApp.MonitorService.MonitorServicesSoap.CheckMinerName(EthMonitorApp.MonitorService.CheckMinerNameRequest request) {
            return base.Channel.CheckMinerName(request);
        }
        
        public bool CheckMinerName(string uniqueName) {
            EthMonitorApp.MonitorService.CheckMinerNameRequest inValue = new EthMonitorApp.MonitorService.CheckMinerNameRequest();
            inValue.Body = new EthMonitorApp.MonitorService.CheckMinerNameRequestBody();
            inValue.Body.uniqueName = uniqueName;
            EthMonitorApp.MonitorService.CheckMinerNameResponse retVal = ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).CheckMinerName(inValue);
            return retVal.Body.CheckMinerNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckMinerNameResponse> EthMonitorApp.MonitorService.MonitorServicesSoap.CheckMinerNameAsync(EthMonitorApp.MonitorService.CheckMinerNameRequest request) {
            return base.Channel.CheckMinerNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EthMonitorApp.MonitorService.CheckMinerNameResponse> CheckMinerNameAsync(string uniqueName) {
            EthMonitorApp.MonitorService.CheckMinerNameRequest inValue = new EthMonitorApp.MonitorService.CheckMinerNameRequest();
            inValue.Body = new EthMonitorApp.MonitorService.CheckMinerNameRequestBody();
            inValue.Body.uniqueName = uniqueName;
            return ((EthMonitorApp.MonitorService.MonitorServicesSoap)(this)).CheckMinerNameAsync(inValue);
        }
    }
}
