//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBot.buiducanh {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="buiducanh.IndexSoap")]
    public interface IndexSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateStatus(string type, int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatus", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateStatusAsync(string type, int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewsletter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddNewsletter(string fullName, string email, string gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewsletter", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddNewsletterAsync(string fullName, string email, string gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddToCart(int productId, int quantity, bool addOne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int productId, int quantity, bool addOne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateCart(int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateCartAsync(int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RemoveCart(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveCart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RemoveCartAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemFromCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetItemFromCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemFromCart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetItemFromCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductFromCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProductFromCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductFromCart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetProductFromCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoneyFromCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMoneyFromCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoneyFromCart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMoneyFromCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProductName(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetProductNameAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMenuDetail(int itemId, int category1Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMenuDetailAsync(int itemId, int category1Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetThietBi(int categoryId, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThietBi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetThietBiAsync(int categoryId, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateTag(string title, string createdby, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTag", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateTagAsync(string title, string createdby, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEthMan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetEthMan(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEthMan", ReplyAction="*")]
        System.Threading.Tasks.Task GetEthManAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertMiner(VBot.buiducanh.MinerInfo miner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMiner", ReplyAction="*")]
        System.Threading.Tasks.Task InsertMinerAsync(VBot.buiducanh.MinerInfo miner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMiners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMiners(string email, bool fullData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMiners", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMinersAsync(string email, bool fullData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MinerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailIdField;
        
        private string nameField;
        
        private string ipField;
        
        private string runningTimeField;
        
        private string ethereumStatsField;
        
        private string gpuTemperatureField;
        
        private string poolField;
        
        private string versionField;
        
        private string commentsField;
        
        private string dcrInfoField;
        
        private System.DateTime createdDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
                this.RaisePropertyChanged("EmailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("Ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RunningTime {
            get {
                return this.runningTimeField;
            }
            set {
                this.runningTimeField = value;
                this.RaisePropertyChanged("RunningTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EthereumStats {
            get {
                return this.ethereumStatsField;
            }
            set {
                this.ethereumStatsField = value;
                this.RaisePropertyChanged("EthereumStats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GpuTemperature {
            get {
                return this.gpuTemperatureField;
            }
            set {
                this.gpuTemperatureField = value;
                this.RaisePropertyChanged("GpuTemperature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Pool {
            get {
                return this.poolField;
            }
            set {
                this.poolField = value;
                this.RaisePropertyChanged("Pool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DcrInfo {
            get {
                return this.dcrInfoField;
            }
            set {
                this.dcrInfoField = value;
                this.RaisePropertyChanged("DcrInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndexSoapChannel : VBot.buiducanh.IndexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndexSoapClient : System.ServiceModel.ClientBase<VBot.buiducanh.IndexSoap>, VBot.buiducanh.IndexSoap {
        
        public IndexSoapClient() {
        }
        
        public IndexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateStatus(string type, int id, string value) {
            base.Channel.UpdateStatus(type, id, value);
        }
        
        public System.Threading.Tasks.Task UpdateStatusAsync(string type, int id, string value) {
            return base.Channel.UpdateStatusAsync(type, id, value);
        }
        
        public bool AddNewsletter(string fullName, string email, string gender) {
            return base.Channel.AddNewsletter(fullName, email, gender);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewsletterAsync(string fullName, string email, string gender) {
            return base.Channel.AddNewsletterAsync(fullName, email, gender);
        }
        
        public bool CheckUsername(string username) {
            return base.Channel.CheckUsername(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUsernameAsync(string username) {
            return base.Channel.CheckUsernameAsync(username);
        }
        
        public bool CheckEmail(string email) {
            return base.Channel.CheckEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEmailAsync(string email) {
            return base.Channel.CheckEmailAsync(email);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public bool AddToCart(int productId, int quantity, bool addOne) {
            return base.Channel.AddToCart(productId, quantity, addOne);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int productId, int quantity, bool addOne) {
            return base.Channel.AddToCartAsync(productId, quantity, addOne);
        }
        
        public string UpdateCart(int productId, int quantity) {
            return base.Channel.UpdateCart(productId, quantity);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCartAsync(int productId, int quantity) {
            return base.Channel.UpdateCartAsync(productId, quantity);
        }
        
        public string RemoveCart(int productId) {
            return base.Channel.RemoveCart(productId);
        }
        
        public System.Threading.Tasks.Task<string> RemoveCartAsync(int productId) {
            return base.Channel.RemoveCartAsync(productId);
        }
        
        public string GetItemFromCart() {
            return base.Channel.GetItemFromCart();
        }
        
        public System.Threading.Tasks.Task<string> GetItemFromCartAsync() {
            return base.Channel.GetItemFromCartAsync();
        }
        
        public string GetProductFromCart() {
            return base.Channel.GetProductFromCart();
        }
        
        public System.Threading.Tasks.Task<string> GetProductFromCartAsync() {
            return base.Channel.GetProductFromCartAsync();
        }
        
        public string GetMoneyFromCart() {
            return base.Channel.GetMoneyFromCart();
        }
        
        public System.Threading.Tasks.Task<string> GetMoneyFromCartAsync() {
            return base.Channel.GetMoneyFromCartAsync();
        }
        
        public string GetProductName(int productId) {
            return base.Channel.GetProductName(productId);
        }
        
        public System.Threading.Tasks.Task<string> GetProductNameAsync(int productId) {
            return base.Channel.GetProductNameAsync(productId);
        }
        
        public string GetMenuDetail(int itemId, int category1Id) {
            return base.Channel.GetMenuDetail(itemId, category1Id);
        }
        
        public System.Threading.Tasks.Task<string> GetMenuDetailAsync(int itemId, int category1Id) {
            return base.Channel.GetMenuDetailAsync(itemId, category1Id);
        }
        
        public string GetThietBi(int categoryId, string language) {
            return base.Channel.GetThietBi(categoryId, language);
        }
        
        public System.Threading.Tasks.Task<string> GetThietBiAsync(int categoryId, string language) {
            return base.Channel.GetThietBiAsync(categoryId, language);
        }
        
        public string CreateTag(string title, string createdby, string language) {
            return base.Channel.CreateTag(title, createdby, language);
        }
        
        public System.Threading.Tasks.Task<string> CreateTagAsync(string title, string createdby, string language) {
            return base.Channel.CreateTagAsync(title, createdby, language);
        }
        
        public void GetEthMan(string data) {
            base.Channel.GetEthMan(data);
        }
        
        public System.Threading.Tasks.Task GetEthManAsync(string data) {
            return base.Channel.GetEthManAsync(data);
        }
        
        public void InsertMiner(VBot.buiducanh.MinerInfo miner) {
            base.Channel.InsertMiner(miner);
        }
        
        public System.Threading.Tasks.Task InsertMinerAsync(VBot.buiducanh.MinerInfo miner) {
            return base.Channel.InsertMinerAsync(miner);
        }
        
        public string GetMiners(string email, bool fullData) {
            return base.Channel.GetMiners(email, fullData);
        }
        
        public System.Threading.Tasks.Task<string> GetMinersAsync(string email, bool fullData) {
            return base.Channel.GetMinersAsync(email, fullData);
        }
    }
}
